### ISSUE TITLE
Incluir ejemplos de uso y documentación inicial

### ISSUE THREAD

**Issue by hugoruscitti** [Program-AR/blockly-package#1]
Pensamos que sería buena idea hacer que este repositorio tenga ejemplos
y algo de documentación así como tiene el repositorio de experimentos
que armó Miguel:
- https://github.com/miguelgarcia/blockly-experiments

Lo ideal es que estos ejemplos se puedan ver con claridad en el archivo
README y que se incluyan algunos ejemplos ejecutables.

PD: también habría que modificar el archivo bower.json para que los
ejemplos no formen parte del paquete bower al instalar en otro proyecto.

**Comment by miguelgarcia** [comment]
Integre el repo con las demos y puse una nota en el readme
