### ISSUE TITLE
Hacer que funcione en modo offline

### ISSUE THREAD

**Issue by hugoruscitti** [Program-AR/blockly-package#2]
Actualmente el paquete no funciona de manera totalmente offline, el paquete de bower no expone varios archivos que necesita blockly para funcionar.

Lo ideal es incluir esos archivos en el paquete de bower y además crear alguna regla o comando para reemplazar las URL externas del paquete, por ejemplo la que apunta a blockly-demo:

![hyperterm 2016-09-25 15-38-27](https://cloud.githubusercontent.com/assets/99183/18817434/7cfc4eaa-8336-11e6-8753-2f63b4f5c299.png)

**Comment by hugoruscitti** [comment]
Mike, encontré un parámetro de configuración que nos permite definir esto al momento de instanciar blockly: el parámetro 'media'.

https://developers.google.com/blockly/guides/get-started/web#configuration

Voy a implementarlo en el componente ember-blockly así funciona offline desde ahí.

¿Te parece bien @miguelgarcia  si cerramos este issue así?

**Comment by miguelgarcia** [comment]
Dale si, así no tenemos que toquetear el código para esto !
