### ISSUE TITLE
Incluir assets para que se pueda usar en modo offline

### ISSUE THREAD

**Issue by hugoruscitti** [Program-AR/blockly-package#4]
Investigamos en los issues #2 y hugoruscitti/ember-blockly#1 que blockly
podría funcionar en modo offline, pero aún así necesitamos que el paquete
bower incluya los archivos del directorio 'media':

https://github.com/google/blockly/tree/93168bebc0f7b27ca06f103f5e7da4c5790a516a/media

¿podrías verlo @miguelgarcia?

**Comment by miguelgarcia** [comment]
Agregué al paquete los archivos, desde la versión 0.0.10 en adelante.
